import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hamburgueria burguer service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main>
      {children}
    </main>
  );
}
